server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET}
  access-token-minutes: 15

spring:
  application:
    name: tbs_miniERP_BACK
  profiles:
    active: prod

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
